- topic: sens/thermostaat/kamerTine/temperature
  payload: 21.6
  expected: {measurement: "temp", fields: {value: 21.6}, tags: {room: 'kamerTine'}}
- topic: sens/thermostaat/kamerTine/humidity
  payload: 72
  expected: {measurement: "humidity", fields: {value: 72}, tags: {room: 'kamerTine'}}
- topic: stat/thermostaat/kamerTine/mode
  payload: abc
  expected: {measurement: "mode", fields: {value: 'abc'}, tags: {room: 'kamerTine'}}
- topic: stat/thermostaat/kamerTine/target
  payload: 19.5
  expected: {measurement: "tempTarget", fields: {value: 19.5}, tags: {room: 'kamerTine'}}
- topic: sig/gang/pir
  payload: 19.5
  expected: {measurement: "pir", fields: {value: 1.0}, tags: {room: 'gang'}}
- topic: zigbee2mqtt/Door_02
  payload: '{"battery":100,"battery_low":false,"contact":false,"linkquality":12,"tamper":false,"voltage":3200}'
  # expected: [{'measurement': 'test_pir', 'fields': {'value': 1}, 'tags': {'room': 'Door_02'}},{'measurement': 'test_voltage', 'fields': {'value': 3200}, 'tags': {'sensor': 'Door_02'}}]
  expected:
    - {'measurement': 'Deurcontact', 'fields': {'value': 1.0}, 'tags': {'door': 'voordeur'}}
    - {'measurement': 'voltage', 'fields': {'value': 3200}, 'tags': {'sensor': 'Door_02'}}
- topic: zigbee2mqtt/PIR-hobby
  payload: '{"battery":100,"battery_low":false,"linkquality":57,"occupancy":true,"tamper":false,"voltage":3100}'
  expected:
    - {'measurement': 'pir', 'fields': {'value': 1.0}, 'tags': {'room': 'hobby'}}
    - {'measurement': 'voltage', 'fields': {'value': 3100}, 'tags': {'sensor': 'PIR-hobby'}}
- topic: stat/pooltemp/batt_v
  payload: 4.1
  expected: {measurement: "battV-tempzwembad", fields: {value: 4.1}, tags: {'sensor': 'zwembadtemp'}}
- topic: sens/pooltemp/air
  payload: 23.2
  expected: {measurement: "temp", fields: {value: 23.2}, tags: {room: 'zwembad_air'}}
- topic: stat/zwembad/cover
  payload: open
  expected: {measurement: poolcover, fields: {value: 'open'}, tags: {}}
- topic: sens/thermostaat/badkamer/SENSOR
  payload: '{"Time":"2021-10-07T21:45:29","AM2301":{"Temperature":20.1,"Humidity":69.6},"TempUnit":"C"}'
  expected: 
    - {measurement: "temp", fields: {value: 20.1}, tags: {room: 'badkamer'}}
    - {measurement: "humidity", fields: {value: 69.6}, tags: {room: 'badkamer'}}
- topic: stat/thermostaat/badkamer/target
  payload: 21.5
  expected: {measurement: "tempTarget", fields: {value: 21.5}, tags: {room: 'badkamer'}}
- topic: stat/thermostaat/badkamer/RESULT
  payload: '{"POWER":"ON"}'
  expected: {measurement: "badkamer_droger", fields: {value: 1}, tags: {}}
- topic: stat/thermostaat/badkamer/RESULT
  payload: '{"POWER":"OFF"}'
  expected: {measurement: "badkamer_droger", fields: {value: 0}, tags: {}}
- topic: sens/panel/boven/battery_perc
  payload: 89
  expected: {measurement: "batt_perc", fields: {value: 89}, tags: {'sensor': 'panel boven'}}
- topic: zigbee2mqtt/temp_living
  payload: '{"battery":78,"humidity":55.4,"linkquality":15,"temperature":21.73}'
  expected: 
    - {measurement: "temp", fields: {value: 21.73}, tags: {room: 'living'}}
    - {measurement: "humidity", fields: {value: 55.4}, tags: {room: 'living'}}
    - {measurement: "batt_perc", fields: {value: 78}, tags: {'sensor': 'temp_living'}}
